name: 'github actions build and deploy gh-pages'
on: 
  push:
    branches:
      - main
# 任务
# 任务
jobs:
  login-gittee:
    runs-on: ubuntu-latest
    steps:
    - name: Sync to Gitee
      uses: Yikun/gitee-mirror-action@v1.1
      with:
        # 必选，需要同步的Github用户（源）
        src: git@github.com:sykinggg/notes.git
        # 必选，需要同步到的Gitee的用户（目的）
        dst: git@gitee.com:systudy/notes.git
        # 必选，Gitee公钥对应的私钥，https://gitee.com/profile/sshkeys
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        # 必选，Gitee对应的用于创建仓库的token，https://gitee.com/profile/personal_access_tokens
        dst_token:  ${{ secrets.GITEE_TOKEN }}
  reload-pages:
    needs: login-gittee
    runs-on: ubuntu-latest
    steps:
      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
          # 注意替换为你的 Gitee 用户名
          gitee-username: systudy
          # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          # 注意替换为你的 Gitee 仓库，仓库名严格区分大小写，请准确填写，否则会出错
          gitee-repo: systudy/notes
          # 要部署的分支，默认是 master，若是其他分支，则需要指定（指定的分支必须存在）
          branch: gh_pages
